Sprint 2/issues 4#home
BrightCoders-Institute/s8pf-bcdic23-rn-proyecto-final-team02 pull request #11
Opened 2024-02-26 23:14 UTC by Jherrera11

# Description

What did you implemented/Why did you implemented this:

-Add Home screen
-Add the Interface folder
-Add the data folder 
-Add Card Company Component
-Add Card Work Component
-Add Imagenes 

Examples:

null

## Testing

null
 Example:

null

## Screenshots

![image](https://github.com/BrightCoders-Institute/s8pf-bcdic23-rn-proyecto-final-team02/assets/104850598/1195708e-6f8e-4684-948c-99b4ec6ef62f)

2024-02-26 23:22 UTC, VISOSO2403 requested changes
pass the images through Squoosh to reduce their size and the svg files pass them through SVGOMG to reduce their size and make the application more fluid.

2024-02-26 23:33 UTC, FelixXD2234 requested changes
You have double blank spaces, delete them.
You must put the correct indentation.
Use the close label if you really need it

2024-02-27 01:13 UTC, FelixXD2234 approved these changes
LGTM

2024-02-27 01:32 UTC, VISOSO2403 requested changes
only changes those images, everything else looks fine.

2024-02-27 01:32 UTC, VISOSO2403 commented on src/assets/user-male-avatar.jpg
This image is jpg, change to webp

2024-02-27 01:32 UTC, VISOSO2403 commented on src/assets/wallpainter.jpg
This image is jpg, change to webp

2024-02-27 05:01 UTC, VISOSO2403 approved these changes
LGTM

2024-02-27 05:01 UTC, merged